/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.90
 * Generated at: 2018-09-11 09:11:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class salaryManage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/jsp/Admin/inc/nav_bar.jsp", Long.valueOf(1536657023000L));
    _jspx_dependants.put("/WEB-INF/jsp/Admin/inc/datatable_css.jsp", Long.valueOf(1536657023000L));
    _jspx_dependants.put("/WEB-INF/jsp/Admin/inc/common_js.jsp", Long.valueOf(1536657023000L));
    _jspx_dependants.put("/WEB-INF/jsp/Admin/inc/common_css.jsp", Long.valueOf(1536657023000L));
    _jspx_dependants.put("/WEB-INF/jsp/Admin/inc/left_sidebar.jsp", Long.valueOf(1536657023000L));
    _jspx_dependants.put("/WEB-INF/jsp/Admin/inc/datatable_js.jsp", Long.valueOf(1536657023000L));
    _jspx_dependants.put("/WEB-INF/jsp/Admin/inc/footer.jsp", Long.valueOf(1536657023000L));
    _jspx_dependants.put("/WEB-INF/jsp/Admin/inc/common.jsp", Long.valueOf(1536657023000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"description\"\n");
      out.write("\tcontent=\"Blank Page | Propeller - Admin Dashboard\">\n");
      out.write("<meta content=\"width=device-width, initial-scale=1, user-scalable=no\"\n");
      out.write("\tname=\"viewport\">\n");
      out.write("<title>Manage Salary | Payroll</title>\n");
      out.write("<!-- Google icon -->\r\n");
      out.write("<!-- <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\"\r\n");
      out.write("\trel=\"stylesheet\"> -->\r\n");
      out.write("\r\n");
      out.write("<!-- Google Icons CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/Admin/google-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"css/Admin/iconfont/material-icons.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"css/Admin/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Propeller css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/Admin/propeller.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Propeller theme css-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"css/Admin/propeller-theme.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Propeller admin theme css-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"css/Admin/propeller-admin.css\">\r\n");
      out.write("\r\n");
      out.write('\n');
      out.write("<!-- DataTables css-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"css/Admin/Data Table/dataTables.bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"css/Admin/responsive.bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"css/Admin/Data Table/select.dataTables.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"css/Admin/Data Table/buttons.bootstrap.min.css\">\t\r\n");
      out.write("\t\r\n");
      out.write("<!-- Propeller dataTables css-->\r\n");
      out.write("<!-- <link rel=\"stylesheet\" type=\"text/css\" -->\r\n");
      out.write("<!-- \thref=\"css/Admin/Data Table/pmd-datatable.css\"> -->\r\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<!-- Header Starts -->\n");
      out.write("\t<!--Start Nav bar -->\n");
      out.write("\t");
      out.write("<nav class=\"navbar navbar-inverse navbar-fixed-top pmd-navbar pmd-z-depth\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <a href=\"javascript:void(0);\" data-target=\"basicSidebar\" data-placement=\"left\" data-position=\"slidepush\"\r\n");
      out.write("               is-open=\"true\" is-open-width=\"1200\"\r\n");
      out.write("               class=\"btn btn-sm pmd-btn-fab pmd-btn-flat pmd-ripple-effect pull-left margin-r8 pmd-sidebar-toggle\"><i\r\n");
      out.write("                    class=\"material-icons md-light\">menu</i></a>\r\n");
      out.write("            <a href=\"index.html\" class=\"navbar-brand\">\r\n");
      out.write("                <a href=\"index.html\" class=\"navbar-brand\">Payroll Management System</a>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</nav>");
      out.write("\n");
      out.write("\t<!--End Nav bar -->\n");
      out.write("\t<!-- Header Ends -->\n");
      out.write("\n");
      out.write("\t<!-- Left sidebar -->\n");
      out.write("\t");
      out.write("<!-- Sidebar Starts -->\r\n");
      out.write("<div class=\"pmd-sidebar-overlay\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- Left sidebar -->\r\n");
      out.write("<aside id=\"basicSidebar\"\r\n");
      out.write("       class=\"pmd-sidebar  sidebar-default pmd-sidebar-slide-push pmd-sidebar-left pmd-sidebar-open bg-fill-darkblue sidebar-with-icons\"\r\n");
      out.write("       role=\"navigation\">\r\n");
      out.write("    <ul class=\"nav pmd-sidebar-nav\">\r\n");
      out.write("\r\n");
      out.write("        <!-- User info -->\r\n");
      out.write("        <li class=\"dropdown pmd-dropdown pmd-user-info visible-xs visible-md visible-sm visible-lg\">\r\n");
      out.write("            <a aria-expanded=\"false\" data-toggle=\"dropdown\" class=\"btn-user dropdown-toggle media\" data-sidebar=\"true\"\r\n");
      out.write("               aria-expandedhref=\"javascript:void(0);\">\r\n");
      out.write("                <div class=\"media-left\">\r\n");
      out.write("                    <img src=\"images/Admin/user-icon.png\" alt=\"New User\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"media-body media-middle\">Admin</div>\r\n");
      out.write("                <div class=\"media-right media-middle\"><i class=\"dic-more-vert dic\"></i></div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li><a href=\"login.html\">Logout</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li><!-- End user info -->\r\n");
      out.write("\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"index.html\" class=\"pmd-ripple-effect\">\r\n");
      out.write("                <i class=\"media-left media-middle\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" viewBox=\"0 0 48 48\">\r\n");
      out.write("                        <path d=\"M6 26h16V6H6v20zm0 16h16V30H6v12zm20 0h16V22H26v20zm0-36v12h16V6H26z\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </i>\r\n");
      out.write("                <span class=\"media-body\">Dashboard</span></a>\r\n");
      out.write("            </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"dropdown pmd-dropdown\">\r\n");
      out.write("            <a aria-expanded=\"false\" data-toggle=\"dropdown\" class=\"btn-user dropdown-toggle media\" data-sidebar=\"true\"\r\n");
      out.write("               href=\"javascript:void(0);\">\r\n");
      out.write("                <i class=\"media-left media-middle\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" viewBox=\"0 0 48 48\">\r\n");
      out.write("                        <path d=\"M24 24c4.42 0 8-3.59 8-8 0-4.42-3.58-8-8-8s-8 3.58-8 8c0 4.41 3.58 8 8 8zm0 4c-5.33 0-16 2.67-16 8v4h32v-4c0-5.33-10.67-8-16-8z\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </i>\r\n");
      out.write("                <span class=\"media-body\">Manage Staff</span>\r\n");
      out.write("                <div class=\"media-right media-bottom\"><i class=\"dic-more-vert dic\"></i></div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li><a href=\"staff.html\">All Staff</a></li>\r\n");
      out.write("                <li><a href=\"staffNew.html\">Add New</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"dropdown pmd-dropdown\">\r\n");
      out.write("            <a aria-expanded=\"false\" data-toggle=\"dropdown\" class=\"btn-user dropdown-toggle media\" data-sidebar=\"true\"\r\n");
      out.write("               href=\"javascript:void(0);\">\r\n");
      out.write("                <i class=\"media-left media-middle\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" viewBox=\"0 0 48 48\">\r\n");
      out.write("                        <path d=\"M23.6 21.8c-4.54-1.18-6-2.39-6-4.29 0-2.18 2.01-3.71 5.4-3.71 3.56 0 4.88 1.7 5 4.2h4.42c-.13-3.45-2.24-6.59-6.42-7.62V6h-6v4.32c-3.88.85-7 3.35-7 7.22 0 4.62 3.83 6.92 9.4 8.26 5.01 1.2 6 2.95 6 4.83 0 1.37-.97 3.57-5.4 3.57-4.12 0-5.75-1.85-5.96-4.2h-4.41c.25 4.38 3.52 6.83 7.37 7.66V42h6v-4.3c3.89-.75 7-3 7-7.11 0-5.66-4.86-7.6-9.4-8.79z\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </i>\r\n");
      out.write("                <span class=\"media-body\">Manage Salary</span></a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li><a href=\"salaryManagePathFirst.do\">Calculate All Staff</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"report.html\" class=\"pmd-ripple-effect\">\r\n");
      out.write("                <i class=\"media-left media-middle\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" viewBox=\"0 0 48 48\">\r\n");
      out.write("                        <path d=\"M32 12l4.59 4.59-9.76 9.75-8-8L4 33.17 6.83 36l12-12 8 8 12.58-12.59L44 24V12z\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </i>\r\n");
      out.write("                <span class=\"media-body\">View Report</span>\r\n");
      out.write("            </a>\r\n");
      out.write("        </li>   \r\n");
      out.write("    </ul>\r\n");
      out.write("</aside><!-- End Left sidebar -->\r\n");
      out.write("<!-- Sidebar Ends -->");
      out.write("\n");
      out.write("\t<!-- Sidebar Ends -->\n");
      out.write("\n");
      out.write("\t<!--content area start-->\n");
      out.write("\t<div id=\"content\" class=\"pmd-content inner-page\">\n");
      out.write("\t\t<!--tab start-->\n");
      out.write("\t\t<div class=\"container-fluid full-width-container blank\">\n");
      out.write("\t\t\t<!-- Title -->\n");
      out.write("\t\t\t<h1 class=\"section-title\" id=\"services\">\n");
      out.write("\t\t\t\t<span>Staff</span>\n");
      out.write("\t\t\t</h1>\n");
      out.write("\t\t\t<!-- End Title -->\n");
      out.write("\n");
      out.write("\t\t\t<!--breadcrum start-->\n");
      out.write("\t\t\t<ol class=\"breadcrumb text-left\">\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"active\">Manage Salary</a></li>\n");
      out.write("\t\t\t\t<li>Calculate All Staff</li>\n");
      out.write("\t\t\t</ol>\n");
      out.write("\t\t\t<!--breadcrum end-->\n");
      out.write("\n");
      out.write("\t\t\t<section class=\"row component-section\">\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\n");
      out.write("\t\t\t\t\t<div class=\"component-box\">\n");
      out.write("\t\t\t\t\t\t<!-- table card example -->\n");
      out.write("\t\t\t\t\t\t<div class=\"pmd-card pmd-z-depth pmd-card-custom-view\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"table-responsive\">\n");
      out.write("\t\t\t\t\t\t\t\t<table id=\"example\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"table pmd-table table-hover table-striped display responsive nowrap\"\n");
      out.write("\t\t\t\t\t\t\t\t\tcellspacing=\"0\" width=\"100%\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>No</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>Name</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>Rank</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>Department</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th>Action</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</section>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- tab end -->\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t<!-- content area end -->\n");
      out.write("\n");
      out.write("\t<!-- Footer Starts -->\n");
      out.write("\t");
      out.write("<footer class=\"admin-footer\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<ul class=\"list-unstyled list-inline\">\r\n");
      out.write("\t\t\t\t<li><span class=\"pmd-card-subtitle-text\">Payroll\r\n");
      out.write("\t\t\t\t\t\tManagement System &copy; <span class=\"auto-update-year\"></span>.\r\n");
      out.write("\t\t\t\t\t\tAll Rights Reserved.\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t<h3 class=\"pmd-card-subtitle-text\">\r\n");
      out.write("\t\t\t\t\t\tLicensed under <a href=\"https://opensource.org/licenses/MIT\"\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_blank\">MIT license.</a>\r\n");
      out.write("\t\t\t\t\t</h3></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"pull-right for-support\"><a\r\n");
      out.write("\t\t\t\t\thref=\"mailto:support@ictti.site\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<svg x=\"0px\" y=\"0px\" width=\"38px\" height=\"38px\"\r\n");
      out.write("\t\t\t\t\t\t\t\tviewBox=\"0 0 38 38\" enable-background=\"new 0 0 38 38\">\r\n");
      out.write("                            <g>\r\n");
      out.write("                                <path fill=\"#A5A4A4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\td=\"M25.621,21.085c-0.642-0.682-1.483-0.682-2.165,0c-0.521,0.521-1.003,1.002-1.524,1.523\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc-0.16,0.16-0.24,0.16-0.44,0.08c-0.321-0.2-0.683-0.32-1.003-0.521c-1.483-0.922-2.726-2.125-3.809-3.488\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc-0.521-0.681-1.002-1.402-1.363-2.205c-0.04-0.16-0.04-0.24,0.08-0.4c0.521-0.481,1.002-1.003,1.524-1.483\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc0.721-0.722,0.721-1.524,0-2.246c-0.441-0.44-0.842-0.842-1.203-1.202c-0.441-0.441-0.842-0.842-1.243-1.243\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc-0.642-0.642-1.483-0.642-2.165,0c-0.521,0.521-1.002,1.002-1.524,1.523c-0.481,0.481-0.722,1.043-0.802,1.685\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc-0.08,1.042,0.16,2.085,0.521,3.047c0.762,2.085,1.925,3.849,3.328,5.532c1.884,2.286,4.17,4.05,6.815,5.333\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc1.203,0.562,2.406,1.002,3.729,1.123c0.922,0.04,1.724-0.201,2.365-0.923c0.441-0.521,0.923-0.922,1.403-1.403\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc0.682-0.722,0.682-1.563,0-2.245C27.265,22.729,26.423,21.927,25.621,21.085z\" />\r\n");
      out.write("                                <path fill=\"#A5A4A4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\td=\"M32.437,5.568C28.869,2,24.098-0.005,19.005-0.005S9.182,2,5.573,5.568C2.005,9.177,0,13.908,0,19\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ts1.965,9.823,5.573,13.432c3.568,3.568,8.34,5.573,13.432,5.573s9.823-1.965,13.431-5.573\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tC39.854,25.014,39.854,12.985,32.437,5.568z M30.299,30.294c-3.003,3.045-7.021,4.695-11.293,4.695\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc-4.272,0-8.291-1.65-11.294-4.695C4.666,27.29,3.016,23.271,3.016,19c0-4.272,1.649-8.291,4.695-11.294\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc3.003-3.003,7.022-4.695,11.294-4.695c4.272,0,8.291,1.649,11.293,4.695C36.56,13.924,36.56,24.075,30.299,30.294z\" />\r\n");
      out.write("                            </g>\r\n");
      out.write("                        </svg>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pmd-card-subtitle-text\">For Support</span>\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"pmd-card-title-text\">support@ictti.site</h3>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>");
      out.write("\n");
      out.write("\t<!-- Footer Ends -->\n");
      out.write("\n");
      out.write("\t<!-- Scripts Starts -->\n");
      out.write("\t");
      out.write("<script src=\"js/Admin/jquery-1.12.2.min.js\"></script>\r\n");
      out.write("<script src=\"js/Admin/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"js/Admin/propeller.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\tvar sPath = window.location.pathname;\r\n");
      out.write("\t\t\t\t\tvar sPage = sPath.substring(sPath.lastIndexOf('/') + 1);\r\n");
      out.write("\t\t\t\t\t$(\".pmd-sidebar-nav\").each(\r\n");
      out.write("\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).find(\"a[href='\" + sPage + \"']\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.parents(\".dropdown\").addClass(\"open\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).find(\"a[href='\" + sPage + \"']\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.parents(\".dropdown\").find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'.dropdown-menu').css(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"display\", \"block\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).find(\"a[href='\" + sPage + \"']\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.parents(\".dropdown\").find(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'a.dropdown-toggle').addClass(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"active\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$(this).find(\"a[href='\" + sPage + \"']\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.addClass(\"active\");\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t$(\".auto-update-year\").html(new Date().getFullYear());\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- Custom Data Table -->\n");
      out.write("\t");
      out.write("<script type=\"text/javascript\" language=\"javascript\"\r\n");
      out.write("\tsrc=\"js/Admin/Data Table/jquery-3.3.1.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\"\r\n");
      out.write("\tsrc=\"js/Admin/Data Table/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\"\r\n");
      out.write("\tsrc=\"js/Admin/Data Table/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\"\r\n");
      out.write("\tsrc=\"js/Admin/Data Table/dataTables.buttons.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\"\r\n");
      out.write("\tsrc=\"js/Admin/Data Table/buttons.bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\"\r\n");
      out.write("\tsrc=\"js/Admin/Data Table/jszip.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\"\r\n");
      out.write("\tsrc=\"js/Admin/Data Table/pdfmake.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\"\r\n");
      out.write("\tsrc=\"js/Admin/Data Table/vfs_fonts.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\"\r\n");
      out.write("\tsrc=\"js/Admin/Data Table/buttons.colVis.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\"\r\n");
      out.write("\tsrc=\"js/Admin/Data Table/buttons.html5.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\"\r\n");
      out.write("\tsrc=\"js/Admin/Data Table/buttons.print.min.js\"></script>");
      out.write("\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t$(document).ready(\n");
      out.write("\t\t\t\tfunction() {\n");
      out.write("\t\t\t\t\tvar sPath = window.location.pathname;\n");
      out.write("\t\t\t\t\tvar sPage = sPath.substring(sPath.lastIndexOf('/') + 1);\n");
      out.write("\t\t\t\t\t$(\".pmd-sidebar-nav\").each(\n");
      out.write("\t\t\t\t\t\t\tfunction() {\n");
      out.write("\t\t\t\t\t\t\t\t$(this).find(\"a[href='\" + sPage + \"']\")\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.parents(\".dropdown\").addClass(\"open\");\n");
      out.write("\t\t\t\t\t\t\t\t$(this).find(\"a[href='\" + sPage + \"']\")\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.parents(\".dropdown\").find(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'.dropdown-menu').css(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"display\", \"block\");\n");
      out.write("\t\t\t\t\t\t\t\t$(this).find(\"a[href='\" + sPage + \"']\")\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.parents(\".dropdown\").find(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t'a.dropdown-toggle').addClass(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"active\");\n");
      out.write("\t\t\t\t\t\t\t\t$(this).find(\"a[href='\" + sPage + \"']\")\n");
      out.write("\t\t\t\t\t\t\t\t\t\t.addClass(\"active\");\n");
      out.write("\t\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t$(\".auto-update-year\").html(new Date().getFullYear());\n");
      out.write("\t\t\t\t});\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t$(document)\n");
      out.write("\t\t\t\t.ready(\n");
      out.write("\t\t\t\t\t\tfunction() {\n");
      out.write("\t\t\t\t\t\t\tvar exampleDatatable = $('#example')\n");
      out.write("\t\t\t\t\t\t\t\t\t.DataTable(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tresponsive : {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdetails : {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype : 'column',\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\ttarget : 'tr'\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\torder : [ 0, 'asc' ],\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tbFilter : true,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tbLengthChange : true,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tpagingType : \"simple\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"paging\" : true,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"searching\" : true,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\"language\" : {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"info\" : \" _START_ - _END_ of _TOTAL_ \",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"sLengthMenu\" : \"<span class='custom-select-title'>Rows per page:</span> <span class='custom-select'> _MENU_ </span>\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"sSearch\" : \"\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"sSearchPlaceholder\" : \"Search\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"paginate\" : {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"sNext\" : \" \",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"sPrevious\" : \" \"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdom : \"<'pmd-card-title'<'data-table-responsive pull-left'><'search-paper pmd-textfield'f>>\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"<'row'<'col-sm-12'tr>>\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ \"<'pmd-card-footer' <'pmd-datatable-pagination' l i p>>\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t/// Select value\n");
      out.write("\t\t\t\t\t\t\t$('.custom-select-info').hide();\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t$(\".data-table-responsive\")\n");
      out.write("\t\t\t\t\t\t\t\t\t.html(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t'<h2 class=\"pmd-card-title-text\">Calculate All Staff</h2>');\n");
      out.write("\t\t\t\t\t\t\t$(\".custom-select-action\")\n");
      out.write("\t\t\t\t\t\t\t\t\t.html(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t'<button class=\"btn btn-sm pmd-btn-fab pmd-btn-flat pmd-ripple-effect btn-primary\" type=\"button\"><i class=\"material-icons pmd-sm\">delete</i></button><button class=\"btn btn-sm pmd-btn-fab pmd-btn-flat pmd-ripple-effect btn-primary\" type=\"button\"><i class=\"material-icons pmd-sm\">more_vert</i></button>');\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\t</script>\n");
      out.write("\t<!-- Scripts Ends -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/Admin/salaryManage.jsp(64,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("i");
      // /WEB-INF/jsp/Admin/salaryManage.jsp(64,10) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SalaryFormBean.begin}", java.lang.Integer.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).intValue());
      // /WEB-INF/jsp/Admin/salaryManage.jsp(64,10) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SalaryFormBean.end}", java.lang.Integer.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).intValue());
      // /WEB-INF/jsp/Admin/salaryManage.jsp(64,10) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setStep(1);
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td class=\"center\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SalaryFormBean.frmStaffList[i-1].staffName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SalaryFormBean.frmStaffList[i-1].rank.rankName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SalaryFormBean.frmStaffList[i-1].dept.deptName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("</td>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><a\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn pmd-btn-raised pmd-ripple-effect btn-info\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"salaryDetail.do\">Salary Detail</a></td>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<td><a\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn pmd-btn-raised pmd-ripple-effect btn-info\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thref=\"personalDetail.do?staffDetailId=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SalaryFormBean.frmStaffList[i-1].id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\">Detail Info</a></td>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
