/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.90
 * Generated at: 2018-09-07 07:10:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class staffDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/jsp/Admin/inc/nav_bar.jsp", Long.valueOf(1536231102000L));
    _jspx_dependants.put("/WEB-INF/jsp/Admin/inc/common_js.jsp", Long.valueOf(1536253118000L));
    _jspx_dependants.put("/WEB-INF/jsp/Admin/inc/common_css.jsp", Long.valueOf(1536253610000L));
    _jspx_dependants.put("/WEB-INF/jsp/Admin/inc/left_sidebar.jsp", Long.valueOf(1536245884000L));
    _jspx_dependants.put("/WEB-INF/jsp/Admin/inc/footer.jsp", Long.valueOf(1536234036000L));
    _jspx_dependants.put("/WEB-INF/jsp/Admin/inc/common.jsp", Long.valueOf(1534840878000L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"description\"\r\n");
      out.write("\tcontent=\"Blank Page | Propeller - Admin Dashboard\">\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1, user-scalable=no\"\r\n");
      out.write("\tname=\"viewport\">\r\n");
      out.write("<title>Staff Detail | Payroll</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Google icon -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"css/Admin/bootstrap.min.css\">\r\n");
      out.write("<!-- Google Icons CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"css/Admin/google-icons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"css/Admin/material-icons.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Propeller css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"css/Admin/propeller.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Propeller theme css-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"css/Admin/propeller-theme.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- Propeller admin theme css-->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"css/Admin/propeller-admin.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Propeller dataTables css-->\r\n");
      out.write("<!-- <link rel=\"stylesheet\" type=\"text/css\" -->\r\n");
      out.write("<!-- \thref=\"css/Admin/pmd-datatable.css\"> -->");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Header Starts -->\r\n");
      out.write("\t<!--Start Nav bar -->\r\n");
      out.write("\t");
      out.write("<nav class=\"navbar navbar-inverse navbar-fixed-top pmd-navbar pmd-z-depth\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("            <a href=\"javascript:void(0);\" data-target=\"basicSidebar\" data-placement=\"left\" data-position=\"slidepush\"\r\n");
      out.write("               is-open=\"true\" is-open-width=\"1200\"\r\n");
      out.write("               class=\"btn btn-sm pmd-btn-fab pmd-btn-flat pmd-ripple-effect pull-left margin-r8 pmd-sidebar-toggle\"><i\r\n");
      out.write("                    class=\"material-icons md-light\">menu</i></a>\r\n");
      out.write("            <a href=\"index.html\" class=\"navbar-brand\">\r\n");
      out.write("                <a href=\"index.html\" class=\"navbar-brand\">Payroll Management System</a>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("\t<!--End Nav bar -->\r\n");
      out.write("\t<!-- Header Ends -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Left sidebar -->\r\n");
      out.write("\t");
      out.write("<!-- Sidebar Starts -->\r\n");
      out.write("<div class=\"pmd-sidebar-overlay\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- Left sidebar -->\r\n");
      out.write("<aside id=\"basicSidebar\"\r\n");
      out.write("       class=\"pmd-sidebar  sidebar-default pmd-sidebar-slide-push pmd-sidebar-left pmd-sidebar-open bg-fill-darkblue sidebar-with-icons\"\r\n");
      out.write("       role=\"navigation\">\r\n");
      out.write("    <ul class=\"nav pmd-sidebar-nav\">\r\n");
      out.write("\r\n");
      out.write("        <!-- User info -->\r\n");
      out.write("        <li class=\"dropdown pmd-dropdown pmd-user-info visible-xs visible-md visible-sm visible-lg\">\r\n");
      out.write("            <a aria-expanded=\"false\" data-toggle=\"dropdown\" class=\"btn-user dropdown-toggle media\" data-sidebar=\"true\"\r\n");
      out.write("               aria-expandedhref=\"javascript:void(0);\">\r\n");
      out.write("                <div class=\"media-left\">\r\n");
      out.write("                    <img src=\"images/Admin/user-icon.png\" alt=\"New User\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"media-body media-middle\">Admin</div>\r\n");
      out.write("                <div class=\"media-right media-middle\"><i class=\"dic-more-vert dic\"></i></div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li><a href=\"login.html\">Logout</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li><!-- End user info -->\r\n");
      out.write("\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"index.html\" class=\"pmd-ripple-effect\">\r\n");
      out.write("                <i class=\"media-left media-middle\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" viewBox=\"0 0 48 48\">\r\n");
      out.write("                        <path d=\"M6 26h16V6H6v20zm0 16h16V30H6v12zm20 0h16V22H26v20zm0-36v12h16V6H26z\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </i>\r\n");
      out.write("                <span class=\"media-body\">Dashboard</span></a>\r\n");
      out.write("            </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"dropdown pmd-dropdown\">\r\n");
      out.write("            <a aria-expanded=\"false\" data-toggle=\"dropdown\" class=\"btn-user dropdown-toggle media\" data-sidebar=\"true\"\r\n");
      out.write("               href=\"javascript:void(0);\">\r\n");
      out.write("                <i class=\"media-left media-middle\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" viewBox=\"0 0 48 48\">\r\n");
      out.write("                        <path d=\"M24 24c4.42 0 8-3.59 8-8 0-4.42-3.58-8-8-8s-8 3.58-8 8c0 4.41 3.58 8 8 8zm0 4c-5.33 0-16 2.67-16 8v4h32v-4c0-5.33-10.67-8-16-8z\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </i>\r\n");
      out.write("                <span class=\"media-body\">Manage Staff</span>\r\n");
      out.write("                <div class=\"media-right media-bottom\"><i class=\"dic-more-vert dic\"></i></div>\r\n");
      out.write("            </a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li><a href=\"staff.html\">All Staff</a></li>\r\n");
      out.write("                <li><a href=\"staffNew.html\">Add New</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"dropdown pmd-dropdown\">\r\n");
      out.write("            <a aria-expanded=\"false\" data-toggle=\"dropdown\" class=\"btn-user dropdown-toggle media\" data-sidebar=\"true\"\r\n");
      out.write("               href=\"javascript:void(0);\">\r\n");
      out.write("                <i class=\"media-left media-middle\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" viewBox=\"0 0 48 48\">\r\n");
      out.write("                        <path d=\"M23.6 21.8c-4.54-1.18-6-2.39-6-4.29 0-2.18 2.01-3.71 5.4-3.71 3.56 0 4.88 1.7 5 4.2h4.42c-.13-3.45-2.24-6.59-6.42-7.62V6h-6v4.32c-3.88.85-7 3.35-7 7.22 0 4.62 3.83 6.92 9.4 8.26 5.01 1.2 6 2.95 6 4.83 0 1.37-.97 3.57-5.4 3.57-4.12 0-5.75-1.85-5.96-4.2h-4.41c.25 4.38 3.52 6.83 7.37 7.66V42h6v-4.3c3.89-.75 7-3 7-7.11 0-5.66-4.86-7.6-9.4-8.79z\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </i>\r\n");
      out.write("                <span class=\"media-body\">Manage Salary</span></a>\r\n");
      out.write("            <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li><a href=\"salaryManagePathFirst.do\">Calculate All Staff</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"report.html\" class=\"pmd-ripple-effect\">\r\n");
      out.write("                <i class=\"media-left media-middle\">\r\n");
      out.write("                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"30\" height=\"30\" viewBox=\"0 0 48 48\">\r\n");
      out.write("                        <path d=\"M32 12l4.59 4.59-9.76 9.75-8-8L4 33.17 6.83 36l12-12 8 8 12.58-12.59L44 24V12z\"/>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </i>\r\n");
      out.write("                <span class=\"media-body\">View Report</span>\r\n");
      out.write("            </a>\r\n");
      out.write("        </li>   \r\n");
      out.write("    </ul>\r\n");
      out.write("</aside><!-- End Left sidebar -->\r\n");
      out.write("<!-- Sidebar Ends -->");
      out.write("\r\n");
      out.write("\t<!-- Sidebar Ends -->\r\n");
      out.write("\r\n");
      out.write("\t<!--content area start-->\r\n");
      out.write("\t<div id=\"content\" class=\"pmd-content inner-page\">\r\n");
      out.write("\t\t<!--tab start-->\r\n");
      out.write("\t\t<div class=\"container-fluid full-width-container blank\">\r\n");
      out.write("\t\t\t<!-- Title -->\r\n");
      out.write("\t\t\t<h1 class=\"section-title\" id=\"services\">\r\n");
      out.write("\t\t\t\t<span>Staff</span>\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t\t<!-- End Title -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!--breadcrum start-->\r\n");
      out.write("\t\t\t<ol class=\"breadcrumb text-left\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\" class=\"active\">Manage Staff</a></li>\r\n");
      out.write("\t\t\t\t<li>Calculate All Staff</li>\r\n");
      out.write("\t\t\t\t<li>Salary Detail</li>\r\n");
      out.write("\t\t\t</ol>\r\n");
      out.write("\t\t\t<!--breadcrum end-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- insert here  -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-12\">\r\n");
      out.write("                <div class=\"page-content profile-edit section-custom\">\r\n");
      out.write("                    <div class=\"pmd-card pmd-z-depth\">\r\n");
      out.write("                        <div class=\"pmd-card-body\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div data-provides=\"fileinput\" class=\"fileinput fileinput-new col-lg-3\">\r\n");
      out.write("                                    <div data-trigger=\"fileinput\"\r\n");
      out.write("                                         class=\"fileinput-preview thumbnail img-circle img-responsive\">\r\n");
      out.write("                                        <img src=\"dist/images/me.jpg\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"action-button\">\r\n");
      out.write("                                                    <span class=\"btn btn-default btn-raised btn-file ripple-effect\">\r\n");
      out.write("                                                        <span class=\"fileinput-new\"><i\r\n");
      out.write("                                                                class=\"material-icons md-light pmd-xs\">add</i></span>\r\n");
      out.write("                                                        <span class=\"fileinput-exists\"><i\r\n");
      out.write("                                                                class=\"material-icons md-light pmd-xs\">mode_edit</i></span>\r\n");
      out.write("                                                        <input type=\"file\" name=\"...\">\r\n");
      out.write("                                                    </span>\r\n");
      out.write("                                        <a data-dismiss=\"fileinput\"\r\n");
      out.write("                                           class=\"btn btn-default btn-raised btn-file ripple-effect fileinput-exists\"\r\n");
      out.write("                                           href=\"javascript:void(0);\"><i\r\n");
      out.write("                                                class=\"material-icons md-light pmd-xs\">close</i></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-lg-9\">\r\n");
      out.write("                                    <span class=\"media-left media-middle\">Personal Information</span>\r\n");
      out.write("                                    <i class=\"media-left media-middle\">\r\n");
      out.write("                                        <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\"\r\n");
      out.write("                                             viewBox=\"0 0 48 48\">\r\n");
      out.write("                                            <path d=\"M24 24c4.42 0 8-3.59 8-8 0-4.42-3.58-8-8-8s-8 3.58-8 8c0 4.41 3.58 8 8 8zm0 4c-5.33 0-16 2.67-16 8v4h32v-4c0-5.33-10.67-8-16-8z\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </i>\r\n");
      out.write("                                    <hr>\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <form class=\"form-horizontal\">\r\n");
      out.write("                                            <fieldset>\r\n");
      out.write("                                                <div class=\"form-group pmd-textfield\">\r\n");
      out.write("                                                    <label for=\"staffName\" class=\"col-lg-4 control-label\">Full\r\n");
      out.write("                                                        Name</label>\r\n");
      out.write("                                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                                        <input type=\"text\" id=\"staffName\" class=\"form-control\"\r\n");
      out.write("                                                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PersonalDetailFormBean.detailStaff.staffName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group pmd-textfield\">\r\n");
      out.write("                                                    <label for=\"nrc\" class=\"col-lg-4 control-label\">NRC</label>\r\n");
      out.write("                                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                                        <input type=\"text\" id=\"nrc\" class=\"form-control\"\r\n");
      out.write("                                                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PersonalDetailFormBean.detailStaff.staffNrc }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group pmd-textfield\">\r\n");
      out.write("                                                    <label for=\"email\" class=\"col-lg-4 control-label\">Email</label>\r\n");
      out.write("                                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                                        <input type=\"email\" id=\"email\" class=\"form-control\" name=\"email\"\r\n");
      out.write("                                                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PersonalDetailFormBean.detailStaff.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group pmd-textfield\">\r\n");
      out.write("                                                    <label class=\"control-label col-lg-4\"\r\n");
      out.write("                                                           for=\"password\">Password</label>\r\n");
      out.write("                                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                                        <input type=\"password\" class=\"form-control empty\" id=\"password\"\r\n");
      out.write("                                                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PersonalDetailFormBean.detailStaff.password }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group pmd-textfield\">\r\n");
      out.write("                                                    <label class=\"control-label col-lg-4\" for=\"confirmPassword\">Confirm\r\n");
      out.write("                                                        Password</label>\r\n");
      out.write("                                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                                        <input type=\"password\" class=\"form-control empty\"\r\n");
      out.write("                                                               id=\"confirmPassword\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PersonalDetailFormBean.detailStaff.password }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group pmd-textfield\">\r\n");
      out.write("                                                    <label for=\"birthDate\" class=\"col-lg-4 control-label\">Date of\r\n");
      out.write("                                                        Birth</label>\r\n");
      out.write("                                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                                        <input type=\"text\" id=\"birthDate\" class=\"form-control\"\r\n");
      out.write("                                                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PersonalDetailFormBean.detailStaff.staffDob }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group pmd-textfield\">\r\n");
      out.write("                                                    <label for=\"religion\"\r\n");
      out.write("                                                           class=\"col-lg-4 control-label\">Religion</label>\r\n");
      out.write("                                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                                        <input type=\"text\" id=\"religion\" class=\"form-control\"\r\n");
      out.write("                                                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PersonalDetailFormBean.detailStaff.religion }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group pmd-textfield\">\r\n");
      out.write("                                                    <label for=\"race\" class=\"col-lg-4 control-label\">Race</label>\r\n");
      out.write("                                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                                        <input type=\"text\" id=\"race\" class=\"form-control\"\r\n");
      out.write("                                                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PersonalDetailFormBean.detailStaff.race }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group pmd-textfield\">\r\n");
      out.write("                                                    <label for=\"phoneNumber\" class=\"col-lg-4 control-label\">Phone\r\n");
      out.write("                                                        Number</label>\r\n");
      out.write("                                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                                        <input type=\"phoneNumber\" id=\"phoneNumber\" class=\"form-control\"\r\n");
      out.write("                                                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PersonalDetailFormBean.detailStaff.phoneNo }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group pmd-textfield\">\r\n");
      out.write("                                                    <label for=\"empStartDate\" class=\"col-lg-4 control-label\">Employment\r\n");
      out.write("                                                        Start Date</label>\r\n");
      out.write("                                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                                        <input type=\"text\" id=\"empStartDate\" class=\"form-control\"\r\n");
      out.write("                                                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PersonalDetailFormBean.detailStaff.employmentStartDate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group pmd-textfield\">\r\n");
      out.write("                                                    <label for=\"currentAdr\" class=\"col-lg-4 control-label\">Current\r\n");
      out.write("                                                        Address </label>\r\n");
      out.write("                                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                                        <input type=\"text\" id=\"currentAdr\" class=\"form-control\"\r\n");
      out.write("                                                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PersonalDetailFormBean.detailStaff.currentAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group pmd-textfield\">\r\n");
      out.write("                                                    <label for=\"parmenentAdr\" class=\"col-lg-4 control-label\">Parmenent\r\n");
      out.write("                                                        Address </label>\r\n");
      out.write("                                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                                        <input type=\"text\" id=\"parmenentAdr\" class=\"form-control\"\r\n");
      out.write("                                                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PersonalDetailFormBean.detailStaff.permanentAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group pmd-textfield\">\r\n");
      out.write("                                                    <label for=\"roleStatus\" class=\"col-lg-4 control-label\">Role\r\n");
      out.write("                                                        Status</label>\r\n");
      out.write("                                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                                        <input type=\"text\" id=\"roleStatus\" class=\"form-control\"\r\n");
      out.write("                                                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(PersonalDetailFormBean.detailStaff.roleStatus) == 0 ? 'Staff' : (PersonalDetailFormBean.detailStaff.roleStatus) == 1 ? 'Treasurer' : 'Persident' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group pmd-textfield\">\r\n");
      out.write("                                                    <label for=\"staffStatus\" class=\"col-lg-4 control-label\">Staff\r\n");
      out.write("                                                        Status</label>\r\n");
      out.write("                                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                                        <input type=\"text\" id=\"staffStatus\" class=\"form-control\"\r\n");
      out.write("                                                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(PersonalDetailFormBean.detailStaff.staffStatus) == 1? 'Active' : 'Disabled' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  disabled>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group pmd-textfield\">\r\n");
      out.write("                                                    <label for=\"deparment\"\r\n");
      out.write("                                                           class=\"col-lg-4 control-label\">Department</label>\r\n");
      out.write("                                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                                        <input type=\"text\" id=\"deparment\" class=\"form-control\"\r\n");
      out.write("                                                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PersonalDetailFormBean.detailStaff.dept.deptName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group pmd-textfield\">\r\n");
      out.write("                                                    <label for=\"qualification\" class=\"col-lg-4 control-label\">Qualification</label>\r\n");
      out.write("                                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                                        <input type=\"text\" id=\"qualification\" class=\"form-control\"\r\n");
      out.write("                                                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PersonalDetailFormBean.detailStaff.qualification.qualificationName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group pmd-textfield\">\r\n");
      out.write("                                                    <label for=\"rank\" class=\"col-lg-4 control-label\">Rank</label>\r\n");
      out.write("                                                    <div class=\"col-lg-8\">\r\n");
      out.write("                                                        <input type=\"text\" id=\"rank\" class=\"form-control\"\r\n");
      out.write("                                                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PersonalDetailFormBean.detailStaff.rank.rankName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </fieldset>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!-- Personal Info Card End -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- tab end -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- content area end -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Footer Starts -->\r\n");
      out.write("\t");
      out.write("<footer class=\"admin-footer\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<ul class=\"list-unstyled list-inline\">\r\n");
      out.write("\t\t\t\t<li><span class=\"pmd-card-subtitle-text\">Payroll\r\n");
      out.write("\t\t\t\t\t\tManagement System &copy; <span class=\"auto-update-year\"></span>.\r\n");
      out.write("\t\t\t\t\t\tAll Rights Reserved.\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t<h3 class=\"pmd-card-subtitle-text\">\r\n");
      out.write("\t\t\t\t\t\tLicensed under <a href=\"https://opensource.org/licenses/MIT\"\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_blank\">MIT license.</a>\r\n");
      out.write("\t\t\t\t\t</h3></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"pull-right for-support\"><a\r\n");
      out.write("\t\t\t\t\thref=\"mailto:support@ictti.site\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<svg x=\"0px\" y=\"0px\" width=\"38px\" height=\"38px\"\r\n");
      out.write("\t\t\t\t\t\t\t\tviewBox=\"0 0 38 38\" enable-background=\"new 0 0 38 38\">\r\n");
      out.write("                            <g>\r\n");
      out.write("                                <path fill=\"#A5A4A4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\td=\"M25.621,21.085c-0.642-0.682-1.483-0.682-2.165,0c-0.521,0.521-1.003,1.002-1.524,1.523\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc-0.16,0.16-0.24,0.16-0.44,0.08c-0.321-0.2-0.683-0.32-1.003-0.521c-1.483-0.922-2.726-2.125-3.809-3.488\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc-0.521-0.681-1.002-1.402-1.363-2.205c-0.04-0.16-0.04-0.24,0.08-0.4c0.521-0.481,1.002-1.003,1.524-1.483\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc0.721-0.722,0.721-1.524,0-2.246c-0.441-0.44-0.842-0.842-1.203-1.202c-0.441-0.441-0.842-0.842-1.243-1.243\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc-0.642-0.642-1.483-0.642-2.165,0c-0.521,0.521-1.002,1.002-1.524,1.523c-0.481,0.481-0.722,1.043-0.802,1.685\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc-0.08,1.042,0.16,2.085,0.521,3.047c0.762,2.085,1.925,3.849,3.328,5.532c1.884,2.286,4.17,4.05,6.815,5.333\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc1.203,0.562,2.406,1.002,3.729,1.123c0.922,0.04,1.724-0.201,2.365-0.923c0.441-0.521,0.923-0.922,1.403-1.403\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc0.682-0.722,0.682-1.563,0-2.245C27.265,22.729,26.423,21.927,25.621,21.085z\" />\r\n");
      out.write("                                <path fill=\"#A5A4A4\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\td=\"M32.437,5.568C28.869,2,24.098-0.005,19.005-0.005S9.182,2,5.573,5.568C2.005,9.177,0,13.908,0,19\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ts1.965,9.823,5.573,13.432c3.568,3.568,8.34,5.573,13.432,5.573s9.823-1.965,13.431-5.573\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tC39.854,25.014,39.854,12.985,32.437,5.568z M30.299,30.294c-3.003,3.045-7.021,4.695-11.293,4.695\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc-4.272,0-8.291-1.65-11.294-4.695C4.666,27.29,3.016,23.271,3.016,19c0-4.272,1.649-8.291,4.695-11.294\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tc3.003-3.003,7.022-4.695,11.294-4.695c4.272,0,8.291,1.649,11.293,4.695C36.56,13.924,36.56,24.075,30.299,30.294z\" />\r\n");
      out.write("                            </g>\r\n");
      out.write("                        </svg>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"pmd-card-subtitle-text\">For Support</span>\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"pmd-card-title-text\">support@ictti.site</h3>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>");
      out.write("\r\n");
      out.write("\t<!-- Footer Ends -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Scripts Starts -->\r\n");
      out.write("\t");
      out.write("<script src=\"js/Admin/jquery-1.12.2.min.js\"></script>\r\n");
      out.write("<script src=\"js/Admin/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"js/Admin/propeller.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
